
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EMS_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Salaries = new HashSet<Salary>();

    }


    public int EmpId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public Nullable<int> DeptId { get; set; }



    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Salary> Salaries { get; set; }

}

}
