//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salary
    {
        public int SalaryId { get; set; }

        [Required(ErrorMessage ="Select Employee")]
        public Nullable<int> EmpId { get; set; }

        [Required(ErrorMessage ="Salary is required")]
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
