
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EMS_Project.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
{

    public int UserId { get; set; }

    [Required(ErrorMessage ="Username is required")]
    public string UserName { get; set; }
    
    [Required(ErrorMessage ="Password is required")]
    public string Password { get; set; }

}

}
